title: "Base de Datos de Impacto Económico de Israel (2020-2024): In"
description: "Este dataset proporciona una visi&oacute;n completa del impacto econ&oacute;mico de Israel durante los &uacute;ltimos cinco a&ntilde;os (2020&ndash;20"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/base-de-datos-de-impacto-economico-de-israel-2020-2024-indicadores-clave-factore"
